### ISSUE TITLE
[Bug] 도와주세요!

### ISSUE THREAD

**Issue by codinginfant** [codestates-seb/seb40_main_024#144]
**버그에 대한 설명**
asset 서비스 부분에서 string -> Long으로 변환한 값을 바로 리턴하고 싶은데 long 타입이 asset으로 변환되지 않는다고 합니다!
자산이 수정된 값을 repository에 넣어주고 싶어요!

**재현방법**
어떤식으로 버그가 발생했는지 순서대로 작성해주세요
ex)
1. asset 서비스 부분에서
2. 실행버튼을 누를 때

제 브랜치에 오늘 한 것까지 올려두었습니다!

**스크린샷**

<img width="786" alt="스크린샷 2022-11-23 오후 11 13 25" src="https://user-images.githubusercontent.com/107476079/203570504-255bd027-5b90-4942-a3f2-f7cb67c7aa33.png">
<img width="682" alt="스크린샷 2022-11-23 오후 11 13 18" src="https://user-images.githubusercontent.com/107476079/203570508-a84acc60-038d-4914-8e50-6d51a31be238.png">

**Comment by JadeMK** [comment]
62c32d1be673ebfb5988239565c26d3a79f8b2e2
윤정님 윗쪽 커밋 확인 부탁드립니다.. 런 확인 후 커밋 하였습니다.

변경사항:

- entity -> nullable false 였던 strValue nullable 로 변경
- dto -> assetValue strValue 어노테이션 위치 변경
- 서비스쪽 런 되도록 리턴값 수정
