### ISSUE TITLE
[Bug] 해당 부분 어떤 타입이 들어가면 좋을 지 모르겠습니다

### ISSUE THREAD

**Issue by codinginfant** [codestates-seb/seb40_main_024#231]
**버그에 대한 설명**
asset 부분 수정되는 로그를 저장해서 리스트로 보여주고 싶어서 구현해봤습니다

**재현방법**
어떤식으로 버그가 발생했는지 순서대로 작성해주세요
ex)
파란색으로 표시된 부분이 문제가 되고 있습니다.
제 깃 브랜치에 우선 푸시해 놨습니다.
감사합니다

**스크린샷**
![스크린샷 2022-12-01 오전 1 38 13](https://user-images.githubusercontent.com/107476079/204856593-9b78c664-1ffc-47bb-9499-9470cbc3d753.png)
![스크린샷 2022-12-01 오전 1 41 17](https://user-images.githubusercontent.com/107476079/204857024-11c1d061-1792-4538-8ecb-9612391389c0.png)

**Comment by JadeMK** [comment]
풀해와서 한번 확인해 볼게요

**Comment by JadeMK** [comment]
<img width="671" alt="Screenshot 2022-12-01 at 1 53 49 am" src="https://user-images.githubusercontent.com/97623334/204861870-7213d58c-993c-4f97-9cae-55cf8664215f.png">

리포지토리 쪽에서 long id 를 받고 있지 않아서 생긴 문제입니다.. 
리포지토리랑 서비스 쪽에 주석 확인해 주세요 윤정님 👍
