### ISSUE TITLE
[Bug] 빌드시 에러

### ISSUE THREAD

**Issue by codinginfant** [codestates-seb/seb40_main_024#39]
**버그에 대한 설명**
콘솔에서 빌드를 눌렀을 때 쓰지도 메서드가 undefined 됐다고 뜹니다

**재현방법**

빌드 버튼 누를 떄 발생합니다

**스크린샷**

![스크린샷 2022-11-15 오후 4 24 01](https://user-images.githubusercontent.com/107476079/201855446-0e15b85b-7cc7-4f39-aa64-bbfd89d482b3.png)

**Comment by JadeMK** [comment]
확인해 보겠습니다!

**Comment by codinginfant** [comment]
깃 허브 reflog 및 파일 백업하니 빌드 에러가 사라졌습니다!
